Repository codesquad-memeber-2020/signup-8, pull requests merged in 2020-03, with the labels that each got.

#16 #1 회원가입 화면 - UI 구성
  iOS/Signup/Signup.xcodeproj/project.pbxproj
  iOS/Signup/Signup.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Signup/Signup.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Signup/Signup.xcodeproj/project.xcworkspace/xcuserdata/hanseop.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/Signup/Signup.xcodeproj/xcuserdata/hanseop.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/Signup/Signup/AppDelegate.swift
  iOS/Signup/Signup/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Signup/Signup/Assets.xcassets/Contents.json
  iOS/Signup/Signup/Base.lproj/LaunchScreen.storyboard
  iOS/Signup/Signup/Base.lproj/Main.storyboard
  iOS/Signup/Signup/Info.plist
  iOS/Signup/Signup/SceneDelegate.swift
  iOS/Signup/Signup/UIExtenstion.swift
  iOS/Signup/Signup/ViewController.swift
  iOS/Signup/SignupTests/Info.plist
  iOS/Signup/SignupTests/SignupTests.swift
Labels: enhancement

#27 #7 UI 구성 (HTML, CSS 완료)
  FE/js/common/constants.js
  FE/js/common/util.js
  FE/js/signup/main.js
  FE/js/signup/signUpView.js
  FE/style/form.css
  FE/style/reset.css
  FE/views/login.html
  FE/views/main.html
  FE/views/signup.html
Labels: FE, feature, fe리뷰요청

#24 #4 회원가입 화면 - 아이디 유효성 체크
  iOS/Signup/Signup.xcodeproj/project.pbxproj
  iOS/Signup/Signup.xcodeproj/project.xcworkspace/xcuserdata/hanseop.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/Signup/Signup/Assets.xcassets/Blue.colorset/Contents.json
  iOS/Signup/Signup/Assets.xcassets/Gray.colorset/Contents.json
  iOS/Signup/Signup/Assets.xcassets/Green.colorset/Contents.json
  iOS/Signup/Signup/Assets.xcassets/Red.colorset/Contents.json
  iOS/Signup/Signup/Controller/ViewController.swift
  iOS/Signup/Signup/Delegate/AppDelegate.swift
  iOS/Signup/Signup/Delegate/IDTextFieldDelegate.swift
  iOS/Signup/Signup/Delegate/SceneDelegate.swift
  iOS/Signup/Signup/Extension/StringExtension.swift
  iOS/Signup/Signup/Extension/UIExtenstion.swift
  iOS/Signup/Signup/Info.plist
  iOS/Signup/Signup/Model/NetworkHandler.swift
  iOS/Signup/Signup/View/Base.lproj/LaunchScreen.storyboard
  iOS/Signup/Signup/View/Base.lproj/Main.storyboard
  iOS/Signup/Signup/View/SignupTextField.swift
  iOS/Signup/Signup/View/StatusLabel.swift
Labels: feature

#34 #33 약관 화면 - UI 구성
  iOS/Signup/Signup.xcodeproj/project.pbxproj
  iOS/Signup/Signup.xcodeproj/project.xcworkspace/xcuserdata/hanseop.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/Signup/Signup/Assets.xcassets/LightGray.colorset/Contents.json
  iOS/Signup/Signup/Controller/PersonalInformationViewController.swift
  iOS/Signup/Signup/Controller/TermsViewController.swift
  iOS/Signup/Signup/Delegate/TermTextViewDelegate.swift
  iOS/Signup/Signup/View/Base.lproj/Main.storyboard
Labels: feature

#29 #8 #10 유효성 검사(아이디, 비밀번호, 관심사, 약관 동의)
  FE/js/common/constants.js
  FE/js/common/fetchReq.js
  FE/js/common/util.js
  FE/js/signup/agreementPopup.js
  FE/js/signup/interest.js
  FE/js/signup/main.js
  FE/js/signup/signUpView.js
  FE/js/signup/validation.js
  FE/style/form.css
  FE/views/signup.html
Labels: FE, feature, fe리뷰요청

#35 관심사 추가 UI 구성
  iOS/Signup/Signup.xcodeproj/project.pbxproj
  iOS/Signup/Signup.xcodeproj/project.xcworkspace/xcuserdata/hanseop.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/Signup/Signup/Controller/InterestViewController.swift
  iOS/Signup/Signup/Controller/TermsViewController.swift
  iOS/Signup/Signup/View/Base.lproj/Main.storyboard
Labels: feature

#36 [iOS] 최종본
  iOS/Signup/Signup.xcodeproj/project.pbxproj
  iOS/Signup/Signup.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Signup/Signup.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Signup/Signup.xcodeproj/project.xcworkspace/xcuserdata/hanseop.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/Signup/Signup.xcodeproj/xcuserdata/hanseop.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  iOS/Signup/Signup.xcodeproj/xcuserdata/hanseop.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/Signup/Signup/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Signup/Signup/Assets.xcassets/Blue.colorset/Contents.json
  iOS/Signup/Signup/Assets.xcassets/Contents.json
  iOS/Signup/Signup/Assets.xcassets/Gray.colorset/Contents.json
  iOS/Signup/Signup/Assets.xcassets/Green.colorset/Contents.json
  iOS/Signup/Signup/Assets.xcassets/LightGray.colorset/Contents.json
  iOS/Signup/Signup/Assets.xcassets/Red.colorset/Contents.json
  iOS/Signup/Signup/Controller/InterestViewController.swift
  iOS/Signup/Signup/Controller/PersonalInformationViewController.swift
  iOS/Signup/Signup/Controller/SignupViewController.swift
  iOS/Signup/Signup/Controller/TermsViewController.swift
  iOS/Signup/Signup/Delegate/AppDelegate.swift
  iOS/Signup/Signup/Delegate/BirthdayTextFieldDelegate.swift
  iOS/Signup/Signup/Delegate/IDTextFieldDelegate.swift
  iOS/Signup/Signup/Delegate/SceneDelegate.swift
  iOS/Signup/Signup/Delegate/TermTextViewDelegate.swift
  iOS/Signup/Signup/Extension/StringExtension.swift
  iOS/Signup/Signup/Extension/UIExtenstion.swift
  iOS/Signup/Signup/Info.plist
  iOS/Signup/Signup/Model/NetworkHandler.swift
  iOS/Signup/Signup/View/Base.lproj/LaunchScreen.storyboard
  iOS/Signup/Signup/View/Base.lproj/Main.storyboard
  iOS/Signup/Signup/View/SignupTextField.swift
  iOS/Signup/Signup/View/StatusLabel.swift
  iOS/Signup/SignupTests/Info.plist
  iOS/Signup/SignupTests/SignupTests.swift
Labels: feature
